# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-07 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envoi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messagerie.Contact')),
            ],
            options={
                'db_table': 'Envoi',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField()),
                ('emetteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_emis', to='messagerie.Contact')),
                ('predecesseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='successeurs', to='messagerie.Message')),
            ],
            options={
                'db_table': 'Message',
            },
        ),
        migrations.AddField(
            model_name='envoi',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinataires', to='messagerie.Message'),
        ),
    ]
