# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-10 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0002_auto_20181207_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='predecesseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='successeurs', to='messagerie.Message'),
        ),
    ]
